spring.config.import=optional:file:.env[.properties]
##
main.datasource.url = ${DB_URL_PROD}
main.datasource.username = ${DB_USERNAME_PROD}
main.datasource.password = ${DB_PASSWORD_PROD}
# server.port=8081
# ui.login.defaultUsername = ${UINAME}
# ui.login.defaultPassword = ${UIPASS}
# jmix.ui.anonymous-allowed=true

# Для отладки (показывает все сообщения AccessLogger)
# logging.level.io.jmix.core.AccessLogger = debug

# Для боевого режима (показывает только важные сообщения)
# logging.level.io.jmix.core.AccessLogger = info